import { ProcurementCenter, Batch, DigitalReport, AlertItem } from '../types';

export const MOCK_CENTERS: ProcurementCenter[] = [
  {
    id: "c-lasalgaon",
    code: "APMC-LASALGAON-01",
    name: "Lasalgaon APMC Main Yard",
    district: "Nashik",
    state: "Maharashtra",
    capacity_mt: 15000,
    active_intake: true,
    total_batches: 142,
    avg_grade_a: 81.2,
    avg_urs: 14.3,
    avg_defect_rate: 4.5,
    assessments_count: 142,
    review_rate: 2.1
  },
  {
    id: "c-pimpalgaon",
    code: "APMC-PIMPALGAON-02",
    name: "Pimpalgaon Baswant Hub",
    district: "Nashik",
    state: "Maharashtra",
    capacity_mt: 12000,
    active_intake: true,
    total_batches: 118,
    avg_grade_a: 76.4,
    avg_urs: 17.8,
    avg_defect_rate: 5.8,
    assessments_count: 118,
    review_rate: 3.4
  },
  {
    id: "c-yeola",
    code: "APMC-YEOLA-03",
    name: "Yeola Sub-Market Yard",
    district: "Nashik",
    state: "Maharashtra",
    capacity_mt: 8500,
    active_intake: true,
    total_batches: 89,
    avg_grade_a: 69.8,
    avg_urs: 21.4,
    avg_defect_rate: 8.8,
    assessments_count: 89,
    review_rate: 7.8
  },
  {
    id: "c-mahuva",
    code: "APMC-MAHUVA-04",
    name: "Mahuva APMC Dehydration Cluster",
    district: "Bhavnagar",
    state: "Gujarat",
    capacity_mt: 9500,
    active_intake: true,
    total_batches: 96,
    avg_grade_a: 84.1,
    avg_urs: 12.0,
    avg_defect_rate: 3.9,
    assessments_count: 96,
    review_rate: 1.9
  },
  {
    id: "c-dindori",
    code: "APMC-DINDORI-05",
    name: "Dindori Direct Procurement Center",
    district: "Nashik",
    state: "Maharashtra",
    capacity_mt: 6000,
    active_intake: true,
    total_batches: 64,
    avg_grade_a: 73.5,
    avg_urs: 20.1,
    avg_defect_rate: 6.4,
    assessments_count: 64,
    review_rate: 4.2
  }
];

export const MOCK_BATCHES: Batch[] = [
  {
    id: "b-0941",
    batch_number: "BATCH-2026-NSK-0941",
    center_id: "c-lasalgaon",
    center_name: "Lasalgaon APMC Main Yard",
    supplier_farmer_id: "MH-NSK-FRM-4892",
    farmer_name: "Rameshwar Eknath Patil",
    farmer_contact: "+91 98224 81920",
    variety: "Nashik Red / Garwa",
    total_lot_weight_kg: 6200,
    vehicle_number: "MH-15-EG-8291",
    arrival_date: "2026-09-28",
    status: "APPROVED",
    grade_a_pct: 83.3,
    urs_pct: 13.3,
    defect_rate_pct: 3.3,
    sample_size: 60,
    confidence: 0.94,
    created_at: "2026-09-28T09:15:00Z"
  },
  {
    id: "b-1102",
    batch_number: "BATCH-2026-PMP-1102",
    center_id: "c-pimpalgaon",
    center_name: "Pimpalgaon Baswant Hub",
    supplier_farmer_id: "MH-PMP-FRM-3194",
    farmer_name: "Balasaheb Kisan Shinde",
    farmer_contact: "+91 97652 14320",
    variety: "Garwa Medium",
    total_lot_weight_kg: 4800,
    vehicle_number: "MH-15-DX-4412",
    arrival_date: "2026-09-27",
    status: "VERIFIED",
    grade_a_pct: 58.0,
    urs_pct: 34.0,
    defect_rate_pct: 8.0,
    sample_size: 60,
    confidence: 0.92,
    created_at: "2026-09-27T11:30:00Z"
  },
  {
    id: "b-0847",
    batch_number: "BATCH-2026-YLA-0847",
    center_id: "c-yeola",
    center_name: "Yeola Sub-Market Yard",
    supplier_farmer_id: "MH-YLA-FRM-9912",
    farmer_name: "Vitthal Dagdu Jadhav",
    farmer_contact: "+91 94231 66782",
    variety: "Late Kharif (Rangda)",
    total_lot_weight_kg: 5100,
    vehicle_number: "MH-15-BV-9102",
    arrival_date: "2026-09-27",
    status: "UNDER_REVIEW",
    grade_a_pct: 43.3,
    urs_pct: 30.0,
    defect_rate_pct: 26.7,
    sample_size: 60,
    confidence: 0.91,
    created_at: "2026-09-27T14:10:00Z"
  },
  {
    id: "b-0431",
    batch_number: "BATCH-2026-MHV-0431",
    center_id: "c-mahuva",
    center_name: "Mahuva APMC Dehydration Cluster",
    supplier_farmer_id: "GJ-BHV-FRM-2091",
    farmer_name: "Dilipbhai Manjibhai Patel",
    farmer_contact: "+91 98980 43219",
    variety: "White Onion (Dehydration)",
    total_lot_weight_kg: 7800,
    vehicle_number: "GJ-04-AT-7819",
    arrival_date: "2026-09-26",
    status: "APPROVED",
    grade_a_pct: 76.0,
    urs_pct: 18.0,
    defect_rate_pct: 6.0,
    sample_size: 60,
    confidence: 0.95,
    created_at: "2026-09-26T16:00:00Z"
  },
  {
    id: "b-0955",
    batch_number: "BATCH-2026-NSK-0955",
    center_id: "c-lasalgaon",
    center_name: "Lasalgaon APMC Main Yard",
    supplier_farmer_id: "MH-NSK-FRM-1029",
    farmer_name: "Shivaji Marutirao Gaikwad",
    farmer_contact: "+91 98501 32984",
    variety: "Nashik Red Bold",
    total_lot_weight_kg: 5500,
    vehicle_number: "MH-15-CP-1144",
    arrival_date: "2026-09-28",
    status: "APPROVED",
    grade_a_pct: 91.0,
    urs_pct: 7.0,
    defect_rate_pct: 2.0,
    sample_size: 60,
    confidence: 0.96,
    created_at: "2026-09-28T08:30:00Z"
  },
  {
    id: "b-0319",
    batch_number: "BATCH-2026-DND-0319",
    center_id: "c-dindori",
    center_name: "Dindori Direct Procurement Center",
    supplier_farmer_id: "MH-DND-FRM-6712",
    farmer_name: "Pravin Bhaskar Bhamre",
    farmer_contact: "+91 99238 77651",
    variety: "Rangda Red",
    total_lot_weight_kg: 4200,
    vehicle_number: "MH-15-TR-2918",
    arrival_date: "2026-09-28",
    status: "PENDING_ASSESSMENT",
    sample_size: 60,
    created_at: "2026-09-28T10:45:00Z"
  }
];

export const MOCK_REPORT_0941: DigitalReport = {
  report_id: "rpt-0941",
  report_code: "RPT-PV-2026-0941",
  document_title: "AI-Assisted Onion Quality Assessment Report",
  prototype_label: "Prototype Digital Quality Assessment Report",
  is_certified_claim: false,
  disclaimer: "PROTOTYPE DEMONSTRATION RECORD: Generated by PYAAZ-VISION SIH prototype. This digital report is based on analyzed sample trays and does not constitute statutory government certification.",
  qr_verification_code: "PV-VERIFY-2026-NSK-0941-VALID",
  created_at: "2026-09-28T09:42:15Z",
  batch_info: {
    batch_id: "b-0941",
    batch_number: "BATCH-2026-NSK-0941",
    supplier_farmer_id: "MH-NSK-FRM-4892",
    farmer_name: "Rameshwar Eknath Patil",
    farmer_contact: "+91 98224 81920",
    variety: "Nashik Red / Garwa",
    total_lot_weight_kg: 6200,
    vehicle_number: "MH-15-EG-8291",
    arrival_date: "2026-09-28",
    final_status: "APPROVED"
  },
  procurement_center: {
    id: "c-lasalgaon",
    code: "APMC-LASALGAON-01",
    name: "Lasalgaon APMC Main Yard",
    district: "Nashik",
    state: "Maharashtra"
  },
  sampling_info: {
    inspector_name: "Inspector Anand K. Deshmukh",
    sample_tray_count: 4,
    sample_size_count: 60,
    reference_object_diameter_mm: 27.0
  },
  ai_findings: {
    total_onions_detected: 60,
    grade_a_count: 50,
    grade_a_pct: 83.3,
    urs_count: 8,
    urs_pct: 13.3,
    damaged_count: 1,
    damaged_pct: 1.7,
    rotten_count: 0,
    rotten_pct: 0.0,
    sprouted_count: 1,
    sprouted_pct: 1.7,
    undersized_count: 5,
    undersized_pct: 8.3,
    defect_count: 2,
    defect_rate_pct: 3.3,
    average_diameter_mm: 55.4,
    average_confidence: 0.94,
    procurement_verdict: "ACCEPTED_GRADE_A",
    recommended_action: "Lot satisfies NAFED / APMC Grade A quality specifications. Approve for priority procurement."
  },
  human_verification: {
    action: "ACCEPT_AI",
    inspector: "Inspector Anand K. Deshmukh",
    final_grade_a: 83.3,
    final_urs: 13.3,
    final_defect: 3.3,
    reason: "Visual manual audit confirms accurate bounding and defect classification.",
    timestamp: "2026-09-28T09:44:10Z"
  }
};

export const MOCK_ALERTS: AlertItem[] = [
  {
    id: "alt-01",
    alert_type: "HIGH_DEFECT_RATE",
    severity: "CRITICAL",
    title: "Critical Defect Threshold Exceeded",
    message: "Batch BATCH-2026-YLA-0847 exceeded 25% total defects (Cuts: 16.7%, Rot: 5.0%). Assessment flagged for arbitration.",
    is_read: false,
    created_at: "18 minutes ago"
  },
  {
    id: "alt-02",
    alert_type: "HIGH_SPROUTING",
    severity: "WARNING",
    title: "Elevated Sprouting Alert in Rangda Stock",
    message: "Pimpalgaon reports elevated 8% dormancy break in stored arrivals due to unseasonal post-monsoon humidity.",
    is_read: false,
    created_at: "1 hour ago"
  },
  {
    id: "alt-03",
    alert_type: "LOW_IMAGE_QUALITY",
    severity: "INFO",
    title: "Recapture Notification (Sample 03)",
    message: "Sub-optimal lighting (< 45 lux) detected during sampling on Yard 4 camera.",
    is_read: true,
    created_at: "3 hours ago"
  }
];
